### ISSUE TITLE
This is awsome!

### ISSUE THREAD

**Issue by Wesztman** [ninadmhatre/byteguide#8]
Not an issue, just wanted to say that your work on this looks awsome! I've been using hostthedocs for a while now and this project seems to solve alot of issues I've had there ❤️ I will take a fork and test it out and hope that I can contribute in some way 😄 (you can close this when read 😉)

**Comment by ninadmhatre** [comment]
Thanks @Wesztman for your encouraging words and thanks for updating README.md.
